export const ALL_PROPOSALS_SET = "ALL_PROPOSALS_SET";
export const PROPOSALS_SET = "PROPOSALS_SET";
export const PROPOSAL_SET = "PROPOSAL_SET";
export const PROPOSAL_TALLY_SET = "PROPOSAL_TALLY_SET";
export const PROPOSER_SET = "PROPOSER_SET";
