export const AUCTION_LIST_SET = "AUCTION_LIST_SET";
export const CURRENT_AUCTION_SET = "CURRENT_AUCTION_SET";
export const BID_AMOUNT_SET = "BID_AMOUNT_SET";
export const BIDDING_LIST_SET = "BIDDING_LIST_SET";
