export const COIN_STATS_FETCH_SUCCESS = "COIN_STATS_FETCH_SUCCESS";
export const COIN_STATS_FETCH_ERROR = "COIN_STATS_FETCH_ERROR";
export const VOLUME_CHART_DATA_SET = "VOLUME_CHART_DATA_SET";
export const VOLUME_CHART_DATA_FETCH_ERROR = "VOLUME_CHART_DATA_FETCH_ERROR";
export const PRICE_CHART_DATA_SET = "PRICE_CHART_DATA_SET";
export const PRICE_CHART_DATA_FETCH_ERROR = "PRICE_CHART_DATA_FETCH_ERROR";
export const RANGE_SET = "RANGE_SET";
export const TOTA_COLLATERAL_LIST_SET = "TOTA_COLLATERAL_LIST_SET";
export const PRICE_CHART_DATA_FETCH_IN_PROGRESS =
  "PRICE_CHART_DATA_FETCH_IN_PROGRESS";
export const VOLUME_CHART_DATA_FETCH_IN_PROGRGESS =
  "VOLUME_CHART_DATA_FETCH_IN_PROGRGESS";
