export const CAUTION_NOTICE_VALUES_SET = "CAUTION_NOTICE_VALUES_SET";
export const DEMAND_COIN_DENOM_SET = "DEMAND_COIN_DENOM_SET";
export const DEMAND_COIN_AMOUNT_SET = "DEMAND_COIN_AMOUNT_SET";
export const OFFER_COIN_DENOM_SET = "OFFER_COIN_DENOM_SET";
export const OFFER_COIN_AMOUNT_SET = "OFFER_COIN_AMOUNT_SET";
export const REVERSE_SET = "REVERSE_SET";
export const SLIPPAGE_SET = "SLIPPAGE_SET";
export const PARAMS_SET = "PARAMS_SET";
export const SLIPPAGE_TOLERANCE_SET = "SLIPPAGE_TOLERANCE_SET;";
export const LIMIT_ORDER_TOGGLE_SET = "LIMIT_ORDER_TOGGLE_SET";
export const LIMIT_PRICE_SET = "LIMIT_PRICE_SET";
export const SWAP_CALCULATIONS_SET = "SWAP_CALCULATIONS_SET";

export const DEFAULT_SLIPPAGE_TOLERANCE = 1;
